### ISSUE TITLE
What's the API going do?

### ISSUE THREAD

**Issue by thebergamo** [open-source-society/ossu-api#11]
Is very importante we got a roadmap to developing the base API.

- Students Profile
- New courses
- New Degrees
- Forums for conversation? (Chat is better using a slack, but is very nice getting the forum for users conversation log)
- Students Badges (Something like this for gamification)

One Idea is using the API to export the graduation. Other pretty nice idea if we got a way to check if the user really finish the courses, for updating yours graduations.

In the future maybe an certificate for the user when he finished the graduation =D

New Ideas for we implementing is very welcomed.

**Comment by ericdouglas** [comment]
@thebergamo do you have access to [Hansoft X](https://hansoftx.com)?

**Comment by mseyne** [comment]
@thebergamo as for the certification/badge system, it could be imaginated by project based p2p vote.
If you got per example 10 vote :+1:  from community, your project if validated and certified, you got the badge. if not, you can get feedback to continue and improve it.

**Comment by evanplaice** [comment]
@mseyne The roadmap really should be added to HansoftX. Moving the content over was mentioned earlier but attention shifted elsewhere.

Most of the basic API functionality has been determined. It would be worthwhile to create a new idea card on HansoftX to capture possible future extensions.

**Comment by mseyne** [comment]
@evanplaice  Yep, I did add it on HansoftX, all the ideas need cleaning and be able to separate basic features from future extensions is important.

**Comment by evanplaice** [comment]
This info has been migrated over to HansoftX
