### ISSUE TITLE
[feat] Courses

### ISSUE THREAD

**Issue by thebergamo** [open-source-society/ossu-api#17]
- [ ] Defining Model's schema
- [ ] Create endpoint API

**Comment by maicoqb** [comment]
How can I help?
I haven't much experience on code collaboration.
:bowtie:

**Comment by oscar-g** [comment]
@maicoqb do you have access to the Slack team and the Hansoft dev board?

**Comment by maicoqb** [comment]
I can't access the Hansoft dev board, seems like the page doesn't exists.

**Comment by oscar-g** [comment]
I'll get those invites out.
