### ISSUE TITLE
roadmap

### ISSUE THREAD

**Issue by mseyne** [open-source-society/ossu-api#22]
Shouldn't we move the roadmap md file to Hansoft as idea ? or make a github wiki ?

**Comment by evanplaice** [comment]
@mseyne Ignore the 'master' branch. Look at the 'develop' branch to gauge the current state of the project.

As per the development Gitflow Workflow outlined in the link in COTRUBUTIONS.md, the 'develop' branch is the mainline for development with feature branches for more in-depth changes and/or experiments.

**Comment by mseyne** [comment]
:+1:  @evanplaice
