### ISSUE TITLE
Installing MongoDb via homebrew alternative?

### ISSUE THREAD

**Issue by interdrift** [open-source-society/ossu-api#24]
Hi guys, I'm interested in learning node.js + express. I'm a WPF desktop developer and as you might know this means i develop with a windows operating system. Is there an alternative way to install mongodb since homebrew looks like a mac program? ( following the steps in installintion.md )

**Comment by evanplaice** [comment]
Installation instructions for Windows haven't been written yet. You'll need to go to the MongoDB website, download, and install the database the same as any other application.

Then you laungh the mongod (ie mongo daemon) and use the args to use ossu-api/data as the data directory.

**Comment by interdrift** [comment]
done,thanks.
