### ISSUE TITLE
The domain name

### ISSUE THREAD

**Issue by mseyne** [open-source-society/ossu-api#5]
Any idea about the name open source society ?

Does open-source-society.org  (or oss.org) the best ? is it legal (if someone deposed the name) ?

and university as a sub part of oss ?  university.oss.org ? open-source-society.org/university ?

I was just thinking about this, and how an international community can take care of legal things like this, I don't know much, someone ?

**Comment by SoullessWaffle** [comment]
It would be awesome if we could somehow procure an oss.org/.net/.com domain name, but unfortunately pretty much all three-letter combinations are taken and it could easily cost [hundreds of dollars to purchase them](http://www.3character.com/price-guide.html).

**Comment by jdinartejesus** [comment]
What about the ossu.org/.net/.com? @SoullessWaffle

**Comment by mseyne** [comment]
Yes, like this we can join big brother with 4 letter and close inspiration.
https://www.p2pu.org/

**Comment by SoullessWaffle** [comment]
@jdinartejesus nope. ossu.io is available at something like $70/year though lol

**Comment by mseyne** [comment]
An other idea, take the time to work on this project and when it is a great plate-forme in which the community believe in, we can do a crowdfunding to acquire the name and server we need for first official deploy.

**Comment by ericdouglas** [comment]
@SoullessWaffle lol ossu.io :+1: 

@mseyne makes sense, we can try it

**Comment by SoullessWaffle** [comment]
@ericdouglas the domain name kinda makes sense though. Newbie goes _in_, computer science graduate comes _out_. **ossu.io** :stuck_out_tongue_closed_eyes:

**Comment by oscar-g** [comment]
I like that haha

**Comment by ericdouglas** [comment]
@SoullessWaffle haha for sure! We **need** this domain :sob:

**Comment by odiefrom** [comment]
That's a pretty awesome domain name heh

**Comment by evanplaice** [comment]
Not gonna lie... ossu.io is pretty cool.

**Comment by SoullessWaffle** [comment]
@evanplaice remember to fill out the form :)
[Link](https://soullesswaffle.typeform.com/to/xuTU4O)

**Comment by evanplaice** [comment]
@SoullessWaffle Done...

**Comment by thebergamo** [comment]
@SoullessWaffle the form is Done =D
http://ossu.io is pretty nice domain name!

@ericdouglas  open an Paypal wallet and we can donate to buy the domain!

**Comment by SoullessWaffle** [comment]
@thebergamo that sounds like a pretty good idea.

**Comment by ericdouglas** [comment]
@thebergamo great! I'll do this. We **nedd** this domain ASAP!

**Comment by SoullessWaffle** [comment]
@ericdouglas how about we do this monday/tuesday so we have some time to get a prototype up and running?

**Comment by evanplaice** [comment]
:+1:

Maybe if anybody ever joins in the #devops channel, they can discuss issues there.

**Comment by ericdouglas** [comment]
@SoullessWaffle ok :+1:
