### ISSUE TITLE
Use mongorito instead of mongoose

### ISSUE THREAD

**Issue by SoullessWaffle** [open-source-society/ossu-api#7]
http://mongorito.com/

Just a thought

**Comment by evanplaice** [comment]
@waterlooSunset already has a userSchema written. It's currently posted on the slack ossu-api channel.

I'm going to see about getting it added as a development branch.

**Comment by SoullessWaffle** [comment]
Can I :+1: myself? I'm going to try either way: :+1: to this.

**Comment by thebergamo** [comment]
We have a slack?

**Comment by SoullessWaffle** [comment]
@thebergamo we do have a Slack and we recieved your form submission. @ericdouglas is AFK right now but he'll invite you to Slack as soon as he's back.

**Comment by ericdouglas** [comment]
Some concerns:

- With mongoose if we have some problem there will be lots of resources avaialable
- If no one know about it, will slow down the development
- Does Mongoorito have the same features that Mongoose has?

For me, Mongoose :+1:

**Comment by thebergamo** [comment]
Maybe is better using a SQL database, like PostgreSQL, because a lot of our data is relational. :/

**Comment by evanplaice** [comment]
I addressed this in the #backend slack channel.

**Comment by thebergamo** [comment]
The discussion is done @evanplaice

**Comment by oscar-g** [comment]
I choose mongoose because the api is well developed and it doesn't depend on the 'harmony' flag, which I believe is not ready for production.

**Comment by evanplaice** [comment]
:+1:
